version: "3"
services:
    safemedia:
        container_name: safemedia
        image: safemedia
        build: .
        ports:
            - 3000:3000
            - 3001:3001
        depends_on:
            - db
    # db:
    #     container_name: database
    #     image: "microsoft/mssql-server-linux"
    #     environment:
    #         SA_PASSWORD: "Aman@2018"
    #         ACCEPT_EULA: "Y"
    #     ports:
    #         - 1433:1433